---
title: "Allison Shapiro"
---

Welcome! This page is still very much under development but I appreciate your patience as I upload information, materials, and resources. Thanks for stopping by (and waiting to cast judgment on this mess of a newborn project)!

*Bio (tl:dr)* - I'm a PhD candidate studying cognitive neuroscience in Dr. Scott Grafton's Action Lab and Brain Imaging Center in the department of Psychological and Brain Sciences at UC Santa Barbara. I'm currently using fMRI and statistical models adapted from behavioral economics to understand how the brain performs value-based decision making. 

*Bio (long-form)* - If you told me a couple years ago that I'd be waist-deep in neuroeconomics data, I'd have told you you were mistaken (and to get your nose out of my future, creep). I entered the field of neuroscience research with a clear and determined purpose in mind - I was going to solve the free will problem. This philosophical issue was first introduced to me in an introductory psychology course I took at UC Berkeley, when a professor explained that if we accept both that physical laws govern the natural world and that brains are natural, biological systems, we may also have to accept all brain processes are similarly governed by physical laws. Balls roll down hills, changes in electrical potentials cause neurons to fire, causing other neurons to fire, eventually causing an action or idea or a feeling. This was followed by the obligatory "but we don't have any idea what consciousness is or how it works, so WHO KNOWS?!" My head shot up, I glanced around the room, scanning my classmates' faces for any sign that they too were suddenly spiraling deep into an existential crisis. Nothing. We'd just been told that the central feature of human experience - the sense of conscious control we experience over our choices and actions - may merely be an illusion. Shouldn't *someone* figure this out? What is in charge of ... me? What does this mean for our legal system and foundational conception of justice? In that moment, I committed to answering these questions, if for nothing else than finally regaining my own peace of mind.

Now motivated by an urgent need to reclaim my sanity by figuring out whether conscious thought gives rise to action, I pursued research assistantships where I could learn how to research both (thought and action) in Dr. Bill Prinzmetal's Attention Laboratory and Dr. Rich Ivry's Cognition and Action Laboratory, both at UC Berkeley.  In the Prinzmetal lab, we investigated how trait variables differentially influence different forms of attention and found that individuals who score low on trait measures of attention (e.g. walking into a room and forgetting how you got there) actually outperform highly focused individuals on tasks that require more globally distributed attention. In the Ivry lab, I studied the role of the cerebellum in temporal motor learning (e.g. how we learn to reach out our hand at just the right speed to catch a baseball). We used motion tracking devices to record hand movements as they reached to intercept objects floating through a virtual environment. I also worked studies that used transcranial magnetic stimulation (TMS) to create transient artificial lesions in different brain regions and observe how this affected motor control. I helped install, develop, and pilot test the first transcranial direct current stimulation (tDCS) system, another form of neurostimulation, at UC Berkeley. Finally equipped with relevant knowledge and reesarch experience, I wrote an honors thesis about how neurositmulation can be used to investigate volitional action and answer quesitons about free will.

After graduating, I moved on to a full-time research specialist position in Dr. Laurel Buxbaum's Cognition and Action Laboratory at Moss Rehabilitation Research Institute at Einstein Hospital in Philadelphia. We studied stroke patients with deficits such as apraxia (deficits in performance and knowledge of skilled actions), aphasia (deficits in language), semantic dementia (a form of dementia that impairs language and semantic memory), and hemispatial neglect (deficits in attention and spatial processing). In the three years I spent at Moss I bolstered my coding skills and learned R and bash shell scripting (with plenty of help from postdocs in the lab), learned neuroimaging methods (structural MRI) and analysis (voxbo, ANTs, FSL), and technical writing for publishing peer-reviewed manuscripts. Some of our most exciting discoveries included separable representations action means and outcomes, how the environment in which we see an object automatically and implicitly intiates context-relevant motor plans, and a distributed network of functionally-specific brain regions supporting gestural actions (i.e. the movement required to use a hammer). Interacting with patients at Moss was an amazing experience that made the direct relationship between neural function and cognition abudandantly, unavoidably clear. Observing the bizarre, yet astonishingly uniform, changes in cognition and awareness that result from brain lesions clearly demonstrated how our thoughts and actions are outputs of a highly structured and seemingly determined system. Lesion region X and you're no longer able to think/do function A, lesion region Y and you're now compelled to think/do function B. I was inundated with ideas for new studies and eagerly applied to graduate school where I could finally develop my own research program.

In 2013, I entered a doctoral program at UC Santa Barbara in Dr. Scott Grafton's Action Lab and Brain Imaging center where I had access to every tool in cognitive neuroscience toolbox. Needless to say- I. was. pumped. I swang for the fences, attempting to nail quesitons about consciousness straight off the bat. And...I struck out, repeatedly, almost exclusively, for my first few years of grad school. It turns out that studying consciousness is *extremely* difficult, maybe those neuroscientists were onto something by avoiding the topic altogether. The primary lesson about consciousness research that I gleaned from my initial efforts is that people are really, really terrible at self-reporting about their thoughts and actions. This surprised me (perhaps more than it should have). For example, in one study I presented images of rewards (e.g. a gift card to Chipotle) and asked participants to decide whether to keep that reward or return it for something else. An auditory tone played at a random time point during the time window while they were deciding and the participants had to note whether they had already comitted to a choice before hearing the tone Then, after the decision making time window, participants reported their choice to keep or return the reward and also whether they finalized a decision before the tone. At first, I found that participants were claiming that they'd made a choice much earlier than I expected (these were intended to be touch choices). So, I added a control condition such that on some trials the tone played at the same time that the reward appeared on the screen, figuring that it would be impossible for participants to make a decision before knowing what the reward was. My participants still insisted that they had already made up their mind before the tone played (i.e. they reported having decided to keep or return a reward that they hadn't even seen yet)! I eventually concluded: trust nobody (attempting to report restrospectively on the timecourse of their own thoughts) (and also that I needed to come up with a different way to answer this question).

I continued beating my head against the problem, developing new ways to get at my research questions. This was an incredibly frustrating and at times demoralizing time. However, this was also a time of incredible growth that uniquely prepared me with 1) a diverse set of skills and expertise entailed by learning various new methodologies and literatures 2) persistence, independence, creativity, and resourcefulness entailed by seemingly endless trouble-shooting and problem solving 3) adaptability entailed by reframing questions in attempts to hit a perpetually moving target 4) knowing when and how to throw out ideas that didn't pan out (even when it hurt) 5) cognitive and emotional resilience entailed by repeatedly facing such a formidable challenge. I also garnered many more tangible skills including expertise in data wrangling and analysis in R, I learned Python to code experimental paradigms and analyze data, I shell scripted image processing pipelines in bash, I learned how to design and conduct fMRI studies and various methods of analyzing BOLD responses (brain activity), I delivered neural stimulation with TMS, and recorded and analyzed muscular responses with electromyography. 

Meanwhile, I unexpectedly discovered that I have a talent and passion for science communication through both verbal and visual mediums, to both expert and non-expert audiences. As a graduate student, I had the opportunity present my research at conference poster sessions and in academic talks, teach classes as the instructor of record, and to mentor high school, undergraduate, and post-baccalaureate research assistants. I have a knack for identifying which bits of information are crucial for communicating a research finding, and how to string those together into a meaningful and memorable story. My favorite part of my job is visualizing data in plots and graphics for manuscripts, conference posters, and slides for research presentations. Learning new and complex topics is challenging enough, but when people have to spend all of their their cognitive reserves just trying to figure out what's going on in a graph, they understand and retain less about what it means for the big picture. I absolutely love (and spend more time than I'm willing to admit) creating beautiful, informative, and honest graphics of research findings.

By the time I proposed my dissertation research, I'd become fascinated by the neuroscience of decision making and decided to table my head-beating against consciousness while I got a handle on how the brain computes a choice. Drawing from modeling methods of behavioral economics, neuroeconomics, and the psychology of value-based decision making, I implemented a series of studies that posed cost-benefit tradeoff scenarios. My current work investigates how the brain derives subjective and objective valuations of potential choices as well as the certainty and ambivalence associated with making decisions. To this end I've integrated more sophisticated and fine-grained multivariate approaches to analyzing large-scale data sets including representational similarity analyses (RSA) and multi-voxel pattern analysis (MVPA) that measure patterns of brain activity ocurring in hundreds of thousands of voxels over thousands of time points. The culmination of these efforts is a final study in which I've attempted to pinpoint the role consciousness in value-based decision making. In this decision making task, participants make value-based choices when value information is masked from conscious awareness (e.g. with continuous flash suppression), but still (potentially) accessed by lower-level perceptual processes.



